# Generated by Django 5.1.5 on 2025-02-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the itinerary', max_length=255)),
                ('destination', models.CharField(help_text='Destination of the trip', max_length=255)),
                ('start_date', models.DateField(help_text='Start date of the trip')),
                ('end_date', models.DateField(help_text='End date of the trip')),
                ('activities', models.TextField(blank=True, help_text='List of activities (comma-separated)')),
                ('expenses', models.TextField(blank=True, help_text='List of expenses (comma-separated)')),
            ],
        ),
    ]
